config/routes.rb
Rails.application.routes.draw do
  root to: 'forecasts#index'
  resources :forecasts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forecast.rb
class Forecast
  attr_reader :provider
  
  def initialize(provider: VisualCrossing.new)
    @provider = provider
  end

  def forecast(input)
    puts "API hit!!!"
    @provider.forecast(input)
  end
end

app/models/forecast_cache.rb
class ForecastCache < ApplicationRecord
end

app/models/forecast_exception.rb
module ForecastException
  class InputInvalidError < StandardError
  end

  class InputEmptyError < StandardError
  end
end

app/models/input_validator.rb
class InputValidator
  include ActiveModel::Validations

  attr_accessor :input

  validates :input, presence: true, format: { with: /\A^[a-zA-Z\s]+$\z/, message: 'Location cannot be null and must be English letters.' }

  def initialize(input:)
    self.input = input
  end
end

app/models/response_parser.rb
class ResponseParser
  class << self
    def parse(response)
      return response if response.is_a?(Hash)
      response = JSON.parse(response).deep_symbolize_keys
      response[:days].first
    end
  end
end

app/models/visual_crossing.rb
class VisualCrossing
  def initialize
    @api_key = Rails.application.credentials.config[:visual_crossing_api_key]
    @base_url = Rails.application.credentials.config[:forecast_api_base_url]
  end

  def forecast(input)
    encoded_input = URI.encode(input)
    res = RestClient.get "#{@base_url}/#{encoded_input}", {params: {key: @api_key}}
    res.body
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :validate_request

  rescue_from JSON::ParserError, with: :api_call_error
  rescue_from RestClient::BadRequest, with: :api_call_error
  rescue_from StandardError, with: :api_call_error
  rescue_from ForecastException::InputInvalidError, with: :input_invalid
  rescue_from ForecastException::InputEmptyError, with: :input_empty

  def index
    @forecast = check_cache
    return if @forecast.present?

    res = Forecast.new.forecast(params[:input])
    @forecast = ResponseParser.parse(res)

    store_cache
  end

  private

  def validate_request
    raise ForecastException::InputEmptyError if params[:input].blank? 
    validation_result = InputValidator.new(input: params[:input])
    raise ForecastException::InputInvalidError.new(validation_result.errors.full_messages.to_sentence) if validation_result.invalid?
  end

  def check_cache
    cache = ForecastCache.where(term: params[:input]).order(:created_at).first
    if cache.blank? or cache.created_at < Constants::CacheTime
      cache.destroy if cache.present?
      return nil
    else
      return {
        datetime: cache.datetime,
        tempmax: cache.tempmax,
        tempmin: cache.tempmin,
        humidity: cache.humidity,
        temp: cache.temp,
        from_cache: true
      }
    end
  end
  
  def input_invalid(e)
    @errors = e.message
    render :index, status: 500
  end

  def input_empty
    @errors = 'Input cannot be empty!'
    render :index, status: 500
  end

  def api_call_error
    @errors = 'Sorry, we couldn\'t find the weather for this search term.'
    render :index, status: 500
  end

  def store_cache
    ForecastCache.create(@forecast.slice(:datetime, :tempmax, :tempmin, :temp, :humidity).merge(term: params[:input]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
  Lables = {:datetime => 'Date', :tempmax => 'Max Temp', :tempmin => 'Min Temp', :temp => 'Temp', :humidity => 'Humidity'}
  def weather_data(data)
    return nil if data.blank?
    html = []
    data.slice(:datetime, :tempmax, :tempmin, :temp ,:humidity).each do |key, value|
      html << content_tag(:li, "#{Lables[key]}: #{value}")
    end

    "<ul>#{html.join}</ul>".html_safe
  end

  def from_cache(data)
    return '<p>From Cache: No</p>'.html_safe if data[:from_cache].blank?
    return '<p>From Cache: Yes</p>'.html_safe
  end
end

app/views/forecasts/index.html.erb
<div class="jumbotron">
  <h1>Weather Forecast</h1>

  <%= render partial: 'forecasts/partials/errors', locals: { forecast: @errors } %>
  <%= render partial: 'forecasts/partials/temperature', locals: { forecast: @forecast } %>

  <%= form_tag forecasts_path, method: :get do %>
    <div class="form-group">
      <label for="exampleInputEmail1">Your location:</label>
      <%= text_field_tag :input, '', class: 'form-control' %>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/forecasts/partials/_errors.html.erb
<% if @errors.present? %>
  <div class="alert alert-danger" role="alert">
    <p><%= @errors %></p>
  </div>
<% end %>

app/views/forecasts/partials/_temperature.html.erb
<% if params[:input] %>
  <h1><%= params[:input] %></h1>
<% end %>
<% if @forecast.present? %>
  <%= weather_data @forecast %>
  <%= from_cache @forecast %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>